mqtt:
  host: 192.168.1.32
  port: 1883
  user: mqtt
  password: mqtt
  topic: 'freeathome/#'

metrics:
  - name: switch_state
    description: 'Power state of switch'
    labels:
      - switch
    topics:
      - topic: 'freeathome/60000F2F2779/ch0000/idp0000'
        labels:
          switch: Heizungspumpe
      - topic: 'freeathome/ABB7F462B789/ch0003/idp0000'
        labels:
          switch: Fußbodenheizungspumpe
